### ISSUE TITLE
Upsert based on 2 primary key columns

### ISSUE THREAD

**Issue by 22ermiller** [timeddilation/dbUpsert#1]
Is there any way to perform an upsert using the dbUpsert function with 2 primary keys? I run the following code:

  dbUpsertTable(
    conn = con,
    name = "Appointments",
    value = appointments_df,
    value_pkey = c("Entity", "ID")
  )

And get the following error:

Error in if (is.na(value_pkey)) { : the condition has length > 1

Looking through your source code I'm not certain where the error code is coming from. But I also noted that in the .dbUpsertStatement() function, I can't tell if it's written to support 2 keys to upsert off of.

**Comment by timeddilation** [comment]
Hey there, sorry, this was a dumb mistake on my end checking the input. It does support multiple column PKeys. I just pushed a new version with this fix. Do you mind checking if this fixes the problem for you? Let me know if the latest version resolves the issue.

**Comment by 22ermiller** [comment]
Just installed the latest version and it works now! Don't think I've had an issue resolved so fast. Impressive!
